package com.el3asas.regym.utils

const val PLAN_ALARM_REQUEST_CODE = 10
const val LONG_PLAN_ALARM_REQUEST_CODE = 11
const val WATER_ALARM_REQUEST_CODE=12
const val WATER_NOTIFICATION_ID=13
const val MAIN_ACTIVITY_PENDING_INTENT = 2
const val ALARM_INTENT_PENDING_INTENT = 3
const val HIDE_NOTIFICATION_REQUEST = 55
const val LONG_PLAN_NOTIFICATION_ID=5
const val PLAN_NOTIFICATION_ID=6
const val PREFS_KEY = "Prefs"
const val INVALID_NAVIGATION_BAR_COLOR = -1
const val SILENT = "silent"

